### PR TITLE
Yas - Architecture on AWS

### PR DESCRIPTION
**Pull request by binhthaiv**
Hi everyone,

Plz help me to review this PR.

**- Architecture Overview of YAS on AWS

- Planning for some Design needs to be added.**

Thanks!

### CODE REVIEW

**Review by nguyenvanhadncntt — APPROVED** [review]

**Comment by VoNhu2901** [comment]
Excuse me :>
Can I ask you a question?
Do you use this image with tool or image from the internet? If it's a tool, what tool do you use?
image

**Comment by binhthaiv** [comment]
@VoNhu2901 
yeah
I drew it by an online tool then export it to image. This is the online tool: https://app.diagrams.net/

**Comment by thiennn** [comment]
thank @binhthaiv but I think it is too complicated for yas

**Comment by binhthaiv** [comment]
I got it. This design above is mine suggest for YAS as an enterprise application with full options for all aspect (backup, monitoring, security, disaster recovery, user management through organization...).

I will update it to simple and effective way: 
   - just keep application in internal EKS
   - default config for backup and security
   - grafana & promethus, opentelemetry as open sources deploy directly in pods eks
   - no read replica, cross AZ, cross region for DB, storage
   - replace CICD by directly use git actions
  
Please help me to rv.  
@thiennn Is it OK ? Thanks you for reviewing.

**Comment by thiennn** [comment]
@binhthaiv look good, other points could consider: 
1. Store media in S3 instead of in db
2. Database use managed service for Postgres

**Pull request closed without merging**
